# Generated by Django 4.2.2 on 2023-06-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_food_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='food_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
