# Generated by Django 4.2.2 on 2023-06-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_food_item_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='small_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
