# Generated by Django 4.2.1 on 2023-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_food_item_small_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
