# Generated by Django 4.2.1 on 2023-07-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='food_qty',
            field=models.IntegerField(blank=True),
        ),
    ]
