# Generated by Django 4.2.1 on 2023-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_cart_food_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='food_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
